### ISSUE TITLE
Add Helm go client wrapper/helper functions

### ISSUE THREAD

**Issue by parthyadav3105** [Kupenstack/kupenstack#2]
#### What would you like to be added:
Add a lightweight helper library for helm go-sdk in `pkg/helm/client.go` which initializes helm client and adds the following helper functions:

`func AddRepoIfNotExist(asName string, url string) error`
`func ListReleases(namespaces ...string) (Release, error)`
`func InstallRelease(name string, repo string, chart string, namespace string, values map[interface{}]interface{}) error`
`func DeleteRelease(name string, namespace string) error`

**Comment by adi0509** [comment]
I am interested in this issue.
Please assign it to me.

**Comment by parthyadav3105** [comment]
Done
